### ISSUE TITLE
Category list urls not working.

### ISSUE THREAD

**Issue by jayalfredprufrock** [rainlab/blog-plugin#106]
I've got a partial that renders a list of categories using the Category List component. Everything works great except the urls that get generated are incorrect. {{ category.url }} uses "default" as the category slug for all categories. If I change the slug manually in the url the category posts page renders fine. What could be going wrong?

**Comment by jayalfredprufrock** [comment]
In the meantime, this seems to be working...

`{{ category.url | replace({'default':category.slug}) }}`

**Comment by jayalfredprufrock** [comment]
I'm now seeing this same problem on the Rainlab.forum plugin. If nobody else is having this issue then I expect some kind of plugin conflict is to blame...

**Comment by kevin-jones** [comment]
We are experiencing a similar problem, where the [blogCategories] component is showing a list of categories, but the links are empty.

When investigating, it appears the component is using `plugins/rainblab/blog/components/categories/items.htm` to render the links, and this relies on `{{ category.url }}` for the link.

When we checked, for some reason `{{ category.url }}` is null, but we do have `{{ category.slug }}` which fixes the problem.

Please can someone say which one should be used, why category.url is null, and whether the component should be updated here or whether we're doing something wrong?

**Comment by zlobec** [comment]
I get the same problem as @kevin-jones ... is there a solution for this?

**Comment by LukeTowers** [comment]
The URL for the categories should be getting set here: https://github.com/rainlab/blog-plugin/blob/master/components/Categories.php#L98.

Have you set the `categoryPage` property of the component correctly?

**Comment by zlobec** [comment]
I'm using the /blog page to also show Post List, which correctly filters the category input.

```
title = "Blog"
url = "/blog/:category?/:page?"
layout = "home"
meta_title = "blog meta title"
meta_description = "blog meta description"
is_hidden = 0

[blogPosts blogList]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :category }}"
postsPerPage = 1
noPostsMessage = "Empty"
sortOrder = "published_at desc"
categoryPage = "blog"
postPage = "blog/post"
==
```

**Comment by LukeTowers** [comment]
@zlobec You're problem is not the same, you aren't using the Categories component.

You are trying to generate a URL to the blog page yourself, and you aren't doing it correctly. The correct way to do that would be to pass the slug to the page function so that it can properly generate the link: `{{ 'blog' | page({'category': category.slug}) }}`. See http://octobercms.com/docs/markup/filter-page#reverse-routing

**Comment by zlobec** [comment]
The same problem occurs when the Category component is included on the page. 

Thanks for the heads up on the reverese routing... I didnt' think to check if this could solve my problem. This page is only my second project in OctoberCMS, and I'm learning. 

I'll try with the Category Component too, to see what happens.

**Comment by LukeTowers** [comment]
@zlobec Did you set the `categoryPage` property of the `categories` component to a CMS page with a URL parameter of `:slug`? https://github.com/rainlab/blog-plugin/blob/master/models/Category.php#L74

**Comment by zlobec** [comment]
Yes, parameter was set correctly. I even created a separate page `/blog/categories` to check if the two components (Post List, Category List) were somehow interfering with each other, but got the same null value for the `category.url`. I've worked around the problem with the same reverse routing hack. Both OctoberCMS and Blog plugin are of the latest version.

**Comment by LukeTowers** [comment]
Did you setup the URL to that separate page with a `slug` url parameter instead of a `category` one? Because that's what is being sent to the reverse routing function in the Category model to generate the URL. 

Failing that, then start throwing debug statements in the Category model and the Categories component to figure out where the breakdown is happening.

**Comment by zlobec** [comment]
The default `:slug` variable works. That doesn't make sense... Why give the option for the variable to be changed if then the component does not work?!?

**Comment by LukeTowers** [comment]
@zlobec It's neither. The [documentation](https://github.com/rainlab/blog-plugin/blob/master/README.md#category-list) recommends you to use the routing param `:slug`, not `:category`. Just because you can use a different routing parameter for the `categoryFilter` doesn't mean we actually officially support that. Having the `categoryFilter` be a property and not always looking at the `:slug` routing parameter is designed so that you could have dedicated category pages with hard coded categories, not necessarily so that you could change the name of the routing parameter used. 

It's simply a feature of how October works that changing that name is technically possible, while not technically supported by this plugin for this particular use case that combines multiple components. Support for changing the name of the parameter that gets passed to the URL generating method by this component could be in theory made possible (a new `categoryParamName` component property to be passed to the `CategoryModel->setUrl()` method). However, I don't see us spending our own time doing so.

**Comment by zlobec** [comment]
Thanks for the explanation. Maybe it would be wise to emphasize in the documentation that the `:slug` variable **should** be set as default and if necessary to use any other value for the parameter name, that it needs to be passed through the reverse routing in order to work correctly with the components. Just to make clear for some newcomers that are still learning OctoberCMS... which by the was is awesome... I get a website online at least 30% faster than any other CMS I've used :) Hats off :)

**Comment by LukeTowers** [comment]
@zlobec if you would like to add that to the documentation with a pull request that would be helpful, thanks!

**Comment by zlobec** [comment]
Ufff... that would also be a first for me... I haven't got the slightest idea how to do that :)

**Comment by LukeTowers** [comment]
@zlobec Go to https://github.com/rainlab/blog-plugin/edit/master/README.md, make your additions, and then click on the "Create a new branch for this commit and start a pull request" after filling out the commit message and description. Google it if you have more questions :) It's really not very difficult at all.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by cbshiles** [comment]
This confused me as well. Would you all still be open to an edit to the README? I'm not sure if I will word it to your liking, but I am willing to try.

**Comment by LukeTowers** [comment]
@cbshiles go for it! I'll review it and let you know if any modifications are required.
