### ISSUE TITLE
Blog doesn't work correctly with Static Menu

### ISSUE THREAD

**Issue by xaddict** [rainlab/blog-plugin#123]
When adding a static menu item linking to a blog category with the following settings:
- title: Blog
- type: Blog category
- reference: Blog (the category I created)
- CMS page: no options

when clicking apply it notifies me about the missing CMS page.

I've tried creating some "Static Pages" and some "core" October Pages with the Component plugged into it but I cannot get the CMS Page dropdown to show anything.

Any ideas?

**Comment by xaddict** [comment]
After some digging around I found the sitemap plugin has the exact same problem. Couldn't the sitemap plugin automatically take some static menus into account?

**Comment by seanthepottingshed** [comment]
This is absolutely doing my head in, anyone got any ideas as to how to solve this?

**Comment by daftspunk** [comment]
Take a look at the [RainLab.Vanilla theme](https://octobercms.com/theme/rainlab-vanilla), the CMS page will populate with this theme. At a bare minimum, the contents must look like this:

```
url = "/blog/category/:slug"

[blogPosts]
categoryFilter = "{{ :slug }}"
==
...
```

This is because the requirements of the page are:

- Must use the `blogPosts` component
- Must use a category filter with a routing parameter. eg: `categoryFilter = "{{ :somevalue }}"`

**Comment by seanthepottingshed** [comment]
Was being a helmet, forgot :

**Comment by daftspunk** [comment]
That'd do it!
