### ISSUE TITLE
How can I use a custom partial?

### ISSUE THREAD

**Issue by andipower** [rainlab/blog-plugin#14]
The plugin uses \components\posts\default.htm as default partial for rendering the posts-list. Where can I adjust this, so that I can use: \components\posts\custom.htm

**Comment by jcouturier** [comment]
For those looking for this same answer, here's what I did in order to use a custom post partial.
For my purposes, I not only wanted a custom post partial, but I wanted different post partials for each category.

Here's what my `\components\posts\default.htm` looks like:

```
{% set post = __SELF__.post %}

{% if post.categories[0].slug == 'lemon' %}
    {% partial "lemon-post" post=post %}
{% else %}
    {% partial "lime-post" post=post %}
{% endif %}
```

Then I have two partials, `lemon-post.htm` and `lime-post.htm`.

If you only want one custom post partial, then your `\components\posts\default.htm` will look like so:

```
{% set post = __SELF__.post %}
{% partial "yourpartialname" post=post %}
```

This works, but I still find editing `\components\posts\default.htm` this way to be rather hacky. If I'm only saving my /theme/ folder in git, now I have modifications outside of my git repo that just make things messy.

**Comment by graker** [comment]
Hi, @jcouturier why don't you just override default.htm partial in your theme? Just create blogPost (or whatever name your component has) directory in your theme/partials and put default.htm there. Then this overridden file will be used. See this doc page for more info: https://octobercms.com/docs/cms/components#overriding-partials

**Comment by jcouturier** [comment]
@graker Well... yes, why don't I?! :)
I didn't know that was an option. I'll just be over here re-reading all the docs.

(thank you).
