### ISSUE TITLE
Feature Request: Preview post as logged in user

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/blog-plugin#193]
Might be overlooking something, but in quite some scenarios it is desirable to see the blog post on the website, without publishing it to the masses. 

Is it currently possible to mark a post for preview, so you can see it on the front-end (as a logged in user with permission to the blog)?

**Comment by AramLoosman** [comment]
+1 I'm also looking for this feature!
It might also be needed for the list views, because often it is important to preview how i.e. the titles break.

**Comment by xseguib** [comment]
+1

**Comment by sunnysingh** [comment]
Any updates on this?

**Comment by daftspunk** [comment]
The support demand for October is increasing, while the available time the maintainers have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- Make a [financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by pvullioud** [comment]
I have done a basic implementation in the component "post". The idea is to allow the access if the current user is logged in the backend.
```	
protected function loadPost() 
{
[...]
if(!BackendAuth::check())
{
	  $post = $post->isPublished();
}
$post = $post->first();
[...]
}
```
https://github.com/pvullioud/blog-plugin/commit/93a5f5336be5c3d115f52f990869a947e06bb35a

My main difficulty to move forward is to calculate the preview URL to add in the backend. Any idea what is the best implementation ? The post plugin could be on multiple page.

**Comment by LukeTowers** [comment]
@pvullioud It would be nice if a permissions check was done instead of just a "is backend user logged in", so something like
```php
if (BackendAuth::getUser()->hasAccess('rainlab.blog.access_posts') {
```

As far as calculating the preview URL, that would have to be defined by the user as far as what CMS page is being used to display the post. We can start with a global setting for that in the plugin settings and then maybe in the future support different pages selected for different categories.

**Comment by pvullioud** [comment]
Instead of creating a settings area that will need many string to translate.
I added the ACL check on the list component too. That means the frontend will also show unPublished articles in the list for Admins with the correct right.
https://github.com/rainlab/blog-plugin/compare/master...pvullioud:master?w=1

**Comment by daftspunk** [comment]
Fixed by https://github.com/rainlab/blog-plugin/pull/316
