### ISSUE TITLE
Unable to change Markdown via fields.yaml when Translatable in affect

### ISSUE THREAD

**Issue by snipiba** [rainlab/blog-plugin#252]
On Posts controller is line (approx 80) where is:
`if ($model instanceof Post && $model->isClassExtendedWith('RainLab.Translate.Behaviors.TranslatableModel')) {`

which means, if you change editor in plugin module fields.yaml file (for example from Markdown to richeditor), and you are using translate plugin both with rainlab blog, then controller override your setting from yaml configuration... 

i know, is not a good way to change editor straight in plugin (all updates will remove all changes),
but when it is maded, then we disable updates for plugin... and this line is cool stuff, when u will use markdown, but when is changed from markdown, then question is, if u guys can check settings before u applied this change to ML markdown editor ;)

for example:
`if ($model instanceof Post && $model->isClassExtendedWith('RainLab.Translate.Behaviors.TranslatableModel') && **$widget->secondaryTabs['fields']['content']['type'] == 'RainLab\Blog\FormWidgets\BlogMarkdown'**) {`

**Comment by daftspunk** [comment]
I'm not sure I understand the problem. As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by xseguib** [comment]
Also if I put a richeditor 
`$widget->secondaryTabs['fields']['content']['type'] = 'richeditor';` @ line 81
is saving correctly in the database table rainlab_translate_attributes but in frontend when switchlocale to spanish for instance, it shows the english (default) content_html

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty
