### ISSUE TITLE
Split mode present on fullscreen

### ISSUE THREAD

**Issue by snipiba** [rainlab/blog-plugin#253]
I tried to remove **mode: split** from fields.yaml what will remove the preview pane from editor. all looks good on basic view, but when its on fullscreen, then editor apears with split function..., on close fullscreen, then split is removed again.

**Comment by daftspunk** [comment]
This is by design, however, I can see that it could be an issue for mobile devices so perhaps this mode should be respected in full screen also.

Regardless, this issue should be logged in the octobercms/october repo as this is where the markdowneditor form widget lives.

Please resubmit this issue to: https://github.com/octobercms/october
