### ISSUE TITLE
Error uploading file ... copy(): Filename cannot be empty

### ISSUE THREAD

**Issue by fcidral** [rainlab/blog-plugin#257]
I got an error when click or drag an image to the post.

Any help here, please?

**Comment by daftspunk** [comment]
Does this only happen in the blog plugin? Try uploading your avatar in the back-end to see if the same issue occurs. This is most likely something caused by your hosting provider, check the error logs for more details.

Otherwise as per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by fcidral** [comment]
Hi Samuel,


thank you for your quickly reply.


I have tried to upload my avatar picture and I got the same error.


do you know how to fix it?  my octobercms is installed on windows server 2012.


Looking forward for your help.


Regards,


Fabio


________________________________

**Comment by daftspunk** [comment]
@tschallacka is our resident Windows Server user. Any idea why this might be happening, Tschallacka?

**Comment by tschallacka** [comment]
yup, I know this error. I need to find the fix for it.

**Comment by tschallacka** [comment]
https://github.com/octobercms/october/pull/1871/commits/77ed5e875681dc451a9338df2ab26586a71b1ab7

**Comment by LukeTowers** [comment]
@tschallacka had a PR (https://github.com/octobercms/october/pull/1871/) made to potentially resolve the issue, but it was closed due to lack of revision to meet the repository's standards. If anyone wants to try again, they're welcome to.

**Comment by LukeTowers** [comment]
@fcidral If I reimplement the changes from octobercms/october#1871 will you test to ensure it works for you?

**Comment by LukeTowers** [comment]
@fcidral Please confirm that octobercms/october#2654 fixed this for you

**Comment by tschallacka** [comment]
Try this one out: https://github.com/octobercms/october/pull/2674

That one is the fix for the images alone.

**Comment by shoguniphicus** [comment]
Thanks, this works great. But because this fix is not yet in october/rain/src/Database/Attach/File.php. It will still break for those attachment.

Inherit this class and override the function with 

`$realPath = empty(trim($uploadedFile->getRealPath()))
                             ? $uploadedFile->getPath() . DIRECTORY_SEPARATOR . $uploadedFile->getFileName()
                             : $uploadedFile->getRealPath();

        $this->putFile($realPath, $this->disk_name);`

Now I can use October on my client's aging Windows server.

**Comment by LukeTowers** [comment]
Thanks for reporting that, I'll fix it for you in the library repository as well.

**Comment by LukeTowers** [comment]
@shoguniphicus I've added the fix to the library as well in https://github.com/octobercms/library/commit/aeacd00c4dab4e054d15f79e41049b832efa1948. Does that solve your problems now?

**Comment by LukeTowers** [comment]
Since @shoguniphicus never replied, and neither did @fcidral I'm going to assume that is issue is resolved.
