### ISSUE TITLE
Realtime Page Update updates too much

### ISSUE THREAD

**Issue by Sieabah** [rainlab/blog-plugin#277]
I've noticed the it actually makes requests every time a single character is changed on the left hand view. This sometimes creates excessive load for the server when typing a sentences fast. There should be some sort of delay between a change and the realtime view updating. It wouldn't have to be long just long enough so you're not making so many requests for typing a, the, so, it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by Sieabah** [comment]
I mean, the issue still exists...?

**Comment by Sieabah** [comment]
@LukeTowers Forgot to tag

**Comment by LukeTowers** [comment]
@Sieabah 
I'm going crazy with the Abandoned tag in order to prompt some movement with these issues. As it stands right now the core team is way too busy with everything to handle every single issue ourselves.

My solution to this is to poke people into actually taking on the issues that are important to them. If an issue isn't important to them anymore, then they won't do anything and everything will continue as it would have anyways. If it is still important to them, then this will act as a reminder that it still needs to be resolved and hopefully motivate people to try and dig deeper into the issue rather than just assume that the free support of an open source project will solve it for them.

If this is still an issue for you, please try debugging it and make a pull request to solve the issue.

**Comment by Sieabah** [comment]
@LukeTowers Leaving it as abandoned is okay I guess but the issue shouldn't be closed. What this issue does is create too many requests per second and can be caught with something like Cloudflare as hitting the site too many times. It's essentially a request every letter including backspacing and deleting a letter.

**Comment by LukeTowers** [comment]
The point of closing it is to minimize the open issues as if no one is going to work on it (i.e. abandoned), then it's just cluttering up the queue. I recognize that this is a potential unwanted behaviour, but if no one is willing to work on fixing it at all, then it's not going to get solved.

If it's an issue for you, which it sounds like it is, then could you please make a pull request with your suggested improvements to resolve the issue?
