### ISSUE TITLE
Want to add Featured image in Blog Home

### ISSUE THREAD

**Issue by sidrahamayun** [rainlab/blog-plugin#297]
Is there any way that i can add on blog home page with blog post list its featured image also.

I want to show my post on blog home page and on home page like this http://i.imgur.com/0I4rlZk.png
is there anyway for this please guide me

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by sidrahamayun** [comment]
why its not the place i am using blog-plugin by rainlab so asking this question regardingly in blog-plugin by rainlab forum

**Comment by LukeTowers** [comment]
My mistake, forgot that the blog plugin links here for support instead of it's own forum on the octobercms.com site. Apologies about that.

**Comment by LukeTowers** [comment]
How are you currently displaying a list of blog posts?

**Comment by sidrahamayun** [comment]
Its ok but you divert me on right place and i found solution here 

http://octobercms.com/forum/post/rainlabblog-listing-posts-with-featured-image
thanks

**Comment by LukeTowers** [comment]
Good to hear!
