### ISSUE TITLE
Imported posts not published

### ISSUE THREAD

**Issue by rodrigogoncalves** [rainlab/blog-plugin#298]
Imported posts are being set as not published, even though the "published date" field in the .csv file is in the past.

**Comment by graker** [comment]
Hi

It happens because besides `published_at` field, `Post` model has boolean `published` field which is missing in the import columns for some reason. I ran into it too when I was migrating my blog to October. If I remember correctly, you can temporarily fix this issue by editing `plugins/rainlab/blog/models/postimport/columns.yaml`. Just add another field at the end: `published: Published` I think it should do the trick and published column will be available in import.

Off course, you will have to add this column to your CSV file. Set its value to 1, then your posts should be imported as published.

**Comment by LukeTowers** [comment]
I would assume that imported posts are not published by default to allow for review of the import before actually publishing them. We could probably look for another field that would tell October that you want them to be automatically published though.

**Comment by rodrigogoncalves** [comment]
Sounds counter intuitive to me, if that is the rationale. Anyway, the easiest fix for me was to update via SQL. Much easier than fiddling with fields in the yaml file.

**Comment by graker** [comment]
@LukeTowers I thought so too. The lack of option is not very friendly anyway. I agree that it would be great to have 'Publish imported posts' checkbox in import settings.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
