### ISSUE TITLE
 There is no way to upload a picture of the post to the front with Vue.js?

### ISSUE THREAD

**Issue by runbee** [rainlab/blog-plugin#343]
I uploaded the picture as the main one and I want to put it on the preview in the list of posts, but apparently there is not such a possibility?

http://prntscr.com/gufz7p

**Comment by LukeTowers** [comment]
How is it not possible? What code are you using that isn't working? Why don't you put a little more effort into asking for help? This question doesn't even ask for help, it just asks for someone to prove it wrong by writing your code for you.

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by runbee** [comment]
I use vuetober. And try to get responce with image. But this functionality is not in this CMS.
