### ISSUE TITLE
Default post.summary|raw manifests as unwanted tags

### ISSUE THREAD

**Issue by joakimbo** [rainlab/blog-plugin#379]
I created this as an issue rather than PR in the case that I might have gotten "snowed in" on how to fix this and would like more views/opinions on a good solution.

So, in the ```components/posts/default.htm``` the summary attribute is handled by the following html and twig:   

```<p class="excerpt">{{ post.summary|raw }}</p>```

This is fine when using the "Excerpt" found in the manage tab of a blog post, however when the excerpt/ summary is generated from the content ```<p></p>``` tags are automatically enclosing the content.
Since the code already encloses with paragraph tags the generated summary isn't allowed to be put in the paragraph tags with the excerpt class and is instead put within its own paragraph tags after the actual excerpt paragraph. For some reason another pair of paragraph tags are also added.

As the default behavior of Excerpt in the manage section of each post does not use markdown and removes tags the easiest solution is to add twig filter "striptags" before "raw" or replacing "raw".

Edit: If we want to lessen any overhead by twig, perhaps stripping the tags in the Post.php model is a better approach.

**Comment by JoakimBo** [comment]
@mightyhaggis You can edit the default component markup after having added your component to a page/layout then placing your cursor somewhere in the string "component" in for example:

{% component 'blogPosts' %}

a fork icon should then appear in the upper right corner, if you click it the component will expand and allow you to edit its default markup.

This issue is to illuminate a problem with how the "summary" of blog posts are generated and displayed.

**Comment by JoakimBo** [comment]
@LukeTowers Yeah my solution was simply to make the the auto-generated summary and the use of the ```<!-- more -->``` behave the same way as the Excerpt from the manage tab (which doesnt allow markup/html). Perhaps these behaving differently is what the authors wanted?

If we allow tags then we need to strip all offending tags (those that cannot be direct children of ```<p>```) before returning from getSummaryAttribute.

    public function getSummaryAttribute()
    {
        $excerpt = $this->excerpt;
        if (strlen(trim($excerpt))) {
            return $excerpt; 
        }

        $more = '';
        if (strpos($this->content_html, $more) !== false) {
            $parts = explode($more, $this->content_html);
            // remove tags here
            return array_get($parts, 0);
        }
        // and remove tags here
        return Html::limit($this->content_html, 600);
    }

**Comment by LukeTowers** [comment]
Does @daftspunk have any input on stripping tags from the autogenerated excerpts of posts?

**Comment by JoakimBo** [comment]
So my original "solution" was rather naive and having looked at it again the actual problem statement might closer to "should the generated summary either through the limiter or use of  end up in the paragraph with the 'excerpt* class".

i.e. when using the excerpt box the text ends up in the correct html paragraph tag as stated.
`<p class="excerpt">{{ post.summary|raw }}</p>`
However when using an auto-generated by character limit or the *more* tag it gets converted through markdown so that the text reside in paragraph tags from the parser and therefore are put outside of the paragraph with the excerpt html tag.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
