### ISSUE TITLE
Plugin breaking image links

### ISSUE THREAD

**Issue by Antar74** [rainlab/blog-plugin#381]
Hello, thanx for your awesome plugin. But oddly enough I'm having trouble with image links after following your video tutorial. After wiring all 3 pages (blog, blog/post, blog/category) when I visit blog/post all images of my website (but those of the blog post itself) display a broken link image. Same goes for the blog/category and for the post count number that should appear next to the category name in the blog page.

Could this be due I missed a parameter somewhere? By the way, my plugin inspectors are different from  yours (those in the video tutorial I mean). Am I using an older or newer version? I don't see a pane for the "Post page parameter" :(

One more thing I noticed is that if I logout and filter the post list with the category name in the blog page the links on the title of the post change to the first link in the inspector list. 

![screen shot 2018-04-17 at 5 37 19 am](https://user-images.githubusercontent.com/34176213/38858262-9b7978c2-4201-11e8-8c33-43158422ee9a.png)
![screen shot 2018-04-17 at 5 37 50 am](https://user-images.githubusercontent.com/34176213/38858263-9ba00988-4201-11e8-9445-da359b605bea.png)

![screen shot 2018-04-17 at 5 35 38 am](https://user-images.githubusercontent.com/34176213/38858098-39f9c1e2-4201-11e8-95eb-04e875ee4283.png)
![screen shot 2018-04-17 at 5 35 10 am](https://user-images.githubusercontent.com/34176213/38858099-3a20652c-4201-11e8-9086-7a01b8cadcdb.png)
![screen shot 2018-04-17 at 5 34 37 am](https://user-images.githubusercontent.com/34176213/38858101-3a44113e-4201-11e8-957f-3947ef67467a.png)

**Comment by Antar74** [comment]
Not sure if this is related, but there is a broken image link also on the blog plugin about page on my october installation. It seems to me there is something wrong with the whole plugin? or could it be my october installation? Help!!! :)

**Comment by LukeTowers** [comment]
What does the rendered HTML for the broken images look like?

**Comment by Antar74** [comment]
Hello Luke thanx for getting in touch! Here you can see the html and the way it get's displayed before and after visiting a post. The trouble seems to be when visiting the post and the category filters. The blog page seems ok with the exception of the number in the post count for each category in the category list.

![screen shot 2018-04-18 at 9 50 56 am](https://user-images.githubusercontent.com/34176213/38933125-898e6d14-42ee-11e8-8204-f0c6e2a46e7a.png)
![screen shot 2018-04-18 at 9 49 50 am](https://user-images.githubusercontent.com/34176213/38933126-89bace7c-42ee-11e8-887f-2b496abefedc.png)

**Comment by LukeTowers** [comment]
Bingo, there's your issue. Because those URL's are relative to the current page (nothing at the start of them) they would only work on the home page because the full URL would resolve to `https://octobercms.if.edu.ly/themes/zanor-mdb4/assets/images/logos/campus-web.png`. However on any other page the full URL would resolve to `https://octobercms.if.edu.ly/my/page/url/here/themes/zanor-mdb4/assets/images/logos/campus-web.png` which obviously doesn't exist. 

This isn't an issue with October, just a misunderstanding of how URL's work. In order to fix this in your case you need to prepend those image paths with `/`, telling the browser that they are root relative URLs, which will make them always resolve to `https://octobercms.if.edu.ly/themes/zanor-mdb4/assets/images/logos/campus-web.png` no matter what page you are on.
