### ISSUE TITLE
Question: Why is registerFormWidgets method missing?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [rainlab/blog-plugin#476]
I see that there are two form Widgets [BlogMarkdown](https://github.com/rainlab/blog-plugin/blob/master/formwidgets/BlogMarkdown.php) and [MLBlogMarkdown.php](https://github.com/rainlab/blog-plugin/blob/master/formwidgets/MLBlogMarkdown.php) used in this plugin however the Plugin.php does not have it's [Form Widget Registration](https://octobercms.com/docs/backend/widgets#form-widget-registration). Is there any specific reason this is as such?

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin because it can be referenced directly by class name: https://github.com/rainlab/blog-plugin/blob/master/models/post/fields.yaml#L30; and either that method of registering widgets didn't exist when the plugin was originally written or we didn't want to encourage other plugins to use those FormWidgets, not sure which was the case. Probably eventually we'll move them into the core and RainLab.Translate plugin respectively as I'd like to do more with markdown directly in the core but for now they're just going to stay unregistered as class references.

**Comment by SaifurRahmanMohsin** [comment]
@LukeTowers Precisely why I had asked, I wanted to include this markdown editor/preview in my own plugin and was wondering why it existed in this plugin than OctoberCMS core. I’ll could make a PR to core if you’d like—making it model-neutral since right now it’s linked to the Post model.

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin if you're interested in doing that go ahead, although note that it will involve four separate PRs: octobercms/october to add the neutral widget, octobercms/docs to document it, rainlab/blog to replace the non-neutral with the new one, and rainlab/translate to include the ML version.

**Comment by dathwa** [comment]
Hello. just installed OCMS 2.2 and we are seeing an error on the "edit post" page.
"A widget class name 'rainlab\blog\formwidgets\mlblogmarkdown' has not been registered"
Related to above?
Any quick fix?
Thanks

**Comment by daftspunk** [comment]
@dathwa This seems like an unrelated issue. Please send an email for support https://octobercms.com/contact
