### ISSUE TITLE
Posts in two columns

### ISSUE THREAD

**Issue by orzech76** [rainlab/blog-plugin#494]
Hello, How can i show the posts inline in two columns in blog list? I tried with "float" but it wrong view in mobile devices. Could you help me a little? My site is https://diabetyk.online/blog/category Thank You. 
m.

**Comment by bennothommo** [comment]
GitHub issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
Slack: https://octobercms-slack.herokuapp.com/
Discord: https://discord.gg/6S777kh

You may also take advantage of our [Premium Support](https://octobercms.com/premium-support) service.

**Comment by bennothommo** [comment]
@orzech76 This section of the documentation should give you guidance on how to do this:
https://octobercms.com/docs/cms/components#customizing-default-markup
