### ISSUE TITLE
Blog Post loop change order in case the page has pagination

### ISSUE THREAD

**Issue by Exodon** [rainlab/blog-plugin#510]
Hi
I´m having a problem on the loop of post when the page has pagination. So basically I have a page with typical content and sidebar. When I go to the second page of the pagination, the loops in the sidebar render other posts instead of showing the same of the first page. 
In this loop  **[blogPosts musicmonth]** that I´m only showing one post, when it goes to the second page of the pagination, nothing is render

**Here some code and image attached to be more easy to understand**
On the content page I´m having a loop to show the first 9 posts .

```
[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :slug }}"
postsPerPage = "9"
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "music/category"
postPage = "music/post"
```

Then on sidebar I´m calling two partials like this : 
```
<article class="widget">
	{% partial 'widgets/music-month' %}
</article>

<article class="widget">
	{% partial 'widgets/music-sidebar' %}
</article>
```
Each one contains a loop to show some posts.

```
[blogPosts musicLatest]
pageNumber = "{{ :page }}"
categoryFilter = "music"
postsPerPage = 5
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "music/category"
postPage = "music/post"
```
```
[blogPosts musicmonth]
pageNumber = "{{ :page }}"
categoryFilter = "music-month"
postsPerPage = 1
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "music/category"
postPage = "music/post"
```
![pagination](https://user-images.githubusercontent.com/3321409/86745606-c2611580-c03a-11ea-8ef3-2dab77a3de75.gif)

**Comment by bennothommo** [comment]
@Exodon the problem lies with this line in all component configurations:
```
pageNumber = "{{ :page }}"
```
Since you have that line in all components, that's effectively making all those components use the same page number from the URL. Instead of switching page for one of the components, you're switching the page for all of them.

You have two options to stop this:

- For the two "music" components, you could lock them to page one by changing `pageNumber` to `1`, if you don't intend for people to browse pages for those components.
- Alternatively, you can have them use another URL parameter by changing `:page` to `:musicPage` or something else. This will mean that you'll have 3 separate page numbers in the URL. however.

**Comment by Exodon** [comment]
thanks @bennothommo is working ... just to understand better your answers, both options that you provide only affect the URL parameters ?

**Comment by bennothommo** [comment]
@Exodon not exactly, the first option changes the page to be locked to page 1, so it would not read the URL parameter anymore. The second option is a change to the URL parameters - essentially, it uses another URL parameters to specify the page number for that particular component.
