### ISSUE TITLE
How to display featured_image in bootstrap 4 modal

### ISSUE THREAD

**Issue by EndiHariadi43** [rainlab/blog-plugin#516]
I want my website users to see the featured_image image in modal-body when they click on each blog title. How to do it? I tried but the picture that appears is always the same when I click on a different title. featured_image does not display images according to existing blog titles ( [https://prntscr.com/tpfiu3](https://prntscr.com/tpfiu3) ). Can anyone help me?
This is the code that I use :

```
<h5 class="card-title">
            <a href="{{ post.url }}" data-toggle="modal" data-target="#XModal"> <b style="font-size:20px;"> {{ post.title }} </b></a>
          </h5>
        
      <div class="modal fade" id="XModal" tabindex="-1" role="dialog" aria-labelledby="cover artikel" aria-hidden="true" >
        <div class="modal-dialog modal-xl">
          <div class="modal-content">
            <div class="modal-body">
              <div class="carousel slide" data-ride="carousel">
                  <div class="carousel-item active">
          
      {% if post.featured_images.count %}
        {% for image in post.featured_images|slice(0, 1) %}
                  <a href="{{ post.url }}">
                <img class="img rounded img-raised d-block img-fluid w-100 lozad" src="{{ image.path| resize(800, 600, { mode: 'auto', quality: '45', extension: 'png' }) }}" alt="{{ image.description != null ? image.description : image.filename }}" title="{{ image.title != null ? image.title : post.title }}" height="600px"  width="800px"/> 
              </a>
                    <div class="carousel-caption">
                      <h5 class="m-0">{{ post.title }}</h5>
                      <p>{{ html_limit( post.summary|raw, 100) }} ...</p>
                    </div>
      
        {% endfor %}{% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

```

**Comment by LukeTowers** [comment]
The problem is that you're generating a modal with the same ID for every slug. 

Change 
`<div class="modal fade" id="XModal" tabindex="-1" role="dialog" aria-labelledby="cover artikel" aria-hidden="true" >`
to 
`<div class="modal fade" id="XModal-slug-{{ post.slug }}" tabindex="-1" role="dialog" aria-labelledby="cover artikel" aria-hidden="true" >`

and 
`<a href="{{ post.url }}" data-toggle="modal" data-target="#XModal"> <b style="font-size:20px;"> {{ post.title }} </b></a>`
to 
`<a href="{{ post.url }}" data-toggle="modal" data-target="#XModal-slug-{{ post.slug }}"> <b style="font-size:20px;"> {{ post.title }} </b></a>`

**Comment by EndiHariadi43** [comment]
Thank you very much LukeTowers, the code you provided works well.
