### ISSUE TITLE
[Bug] Categories not staying checked

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/blog-plugin#52]
Hi, I've noticed that when you check a category for a blog post, the selected Category does not stay checked when you return to the post to edit again - if you then save the post, there are no categories assigned.

There is a forum topic [here](http://octobercms.com/forum/post/roles-are-no-longer-selected-on-the-backend).

This seems to be CMS wide, not just the Blog plugin, but have posted the issue here as this plugin contains the issue.

Thanks

**Comment by jtherczeg** [comment]
I second this issue.

After saving a blog post, the check mark will disappear from the checkbox in the Categories tab, when you reopen it. When you save this post, you must take care of the checking, otherwise the post will not be included in the category.

I'm using OctoberCMS Build 181 and RainLab Blog pugin version 1.0.11

**Comment by DanielHitchen** [comment]
This seems to have been fixed in OctoberCMS build 183
