### ISSUE TITLE
How to inset images in the blog and have them float left with text wrap

### ISSUE THREAD

**Issue by g3rox** [rainlab/blog-plugin#532]
I'd like to inset images into the single blogs but whenever I insert an image, even if its sized very small, I get one line of text that is next to it then the rest of the text is below the image. How can I float left the image with text wrap?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
