### ISSUE TITLE
Google News

### ISSUE THREAD

**Issue by orzech76** [rainlab/blog-plugin#540]
Hello, I`d like to add my blog to Google News. I have an issue with url adres. On my page url https://diabetyk.online/blog/category i  have a list of articles. In this adress Google News doesn`t detect a multiple articles. My artciles pages have url https://diabetyk.online/blog/post/... I thing that problem is in url adres blog/category or blog/post. I quote from Google "As per the Web Location requirements, URLs used for Web Location sections need to regularly link to fresh content.". 
I will be grateful for help 👍 

Best regards,
Maciej Orzechowski

**Comment by bennothommo** [comment]
GitHub issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Discord: https://discord.gg/6S777kh
