### ISSUE TITLE
Change the slug automatically when renaming a blog post

### ISSUE THREAD

**Issue by jtherczeg** [rainlab/blog-plugin#55]
1. Click **New post** in Blog > Posts page.
2. Enter the title of your new blog post. The slug will be automatically filled in.
3. Enter some text in the **Edit** tab of the editor.
4. Click **Save** then **Save and close** to return to the Manage the blog posts screen.
5. Reopen this post you just added.
6. Delete the title of the post and enter a new one.
7. The slug will remain unchanged, it will refer to the old address.

When I delete the slug and I want to save the post with the new title, _"The slug field is requiored"_ message is displayed.

A small improvement would be, when you change the title, the slug also would change automatically.

**Comment by mossadal** [comment]
I'm not entirely sure that this would be a good idea, at least not without some tweaking. I would agree with the above behaviour for *unpublished* posts.

However, imagine that you're running a high-trafic site and change the title of an old, popular post that went viral. There will be many links to the original url, using the original slug floating around. If the slug is changed, then all those links will be dead. If your proposal is implemented, I think it should be with the option of automatically creating a route so that the old url will still point to the same post.

**Comment by vojtasvoboda** [comment]
Totally agree with @mossadal

**Comment by LukeTowers** [comment]
I also agree with @mossadal. If any more convincing arguments can be made, then we'll revisit this.

**Comment by daftspunk** [comment]
Ditto (NACK)
