### ISSUE TITLE
Wrong code format displayed in website

### ISSUE THREAD

**Issue by calebeso** [rainlab/blog-plugin#554]
When I'm making a blog post in my backend application, I got the correctly preview of what should be the code format: 

![correto](https://user-images.githubusercontent.com/53923521/120581885-f0dda100-c401-11eb-9b5f-31ba805d9622.png)

But when I go to the website, this is what is being displayed in the front. Already check possible css alters but no one's found..

![errado](https://user-images.githubusercontent.com/53923521/120581964-110d6000-c402-11eb-8f82-f9f43dea73c0.png)

Any ideia of what could be?

**Comment by daftspunk** [comment]
Hi @calebeso 

This is because the frontend and backend are using a different theme. If you are using the demo theme, take a look at the `javascript/app.js` file and see where it activates code formatting:

```
    /*
     * Init code blocks
     */

    $('pre').each(function () {
        var $this = $(this),
            $code = $this.html(),
            originalValue = $this.html(),
            unescaped = originalValue.replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    
        $this.empty()
        var cm = new CodeMirror(this, {
            value: $code,
            mode: 'twig',
            htmlMode: true,
            lineNumbers: true,
            readOnly: true
        })

        cm.setValue(unescaped)
    })
```

You can apply a different theme here. These themes are supported: https://codemirror.net/demo/theme.html

I hope this helps!

**Comment by calebeso** [comment]
Thanks for replying! 

Problem solved!
