### ISSUE TITLE
The blog can't be access to public 

### ISSUE THREAD

**Issue by sairoko12** [rainlab/blog-plugin#558]
(LATEST BUILD 2.0.21 - Blog 1.5.1)

Hi everyone,

I set up my blog, but I can't see anything when trying to access it from other devices without an admin session, I can only see the content when I have an admin session.

I trying to find any settings about privacy or similar

Any suggestion for this?

**Comment by daftspunk** [comment]
Hi @sairoko12!

This is likely caused by the fact that the blog posts are not in a "published" state. You can click the checkbox under the Manage tab for every post. 

- [X] Published

By design, admins can see the posts when they are not published, this lets them preview the content. It is possible to disable this functionality via the Blog Settings.

Hope this helps!
